name: CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd HireHub-Piro21/
            git pull origin main
            source venv/bin/activate
            pip3 install -r requirements.txt
            python3 manage.py collectstatic --noinput
            sudo systemctl restart hirehub.service
            sudo systemctl restart nginx